### ISSUE TITLE
undefined method `load_file' for PDF::Core::ObjectStore

### ISSUE THREAD

**Issue by cthiel** [prawnpdf/pdf-core#2]
With commit db1c871dac33d94d182d01550f87efb6f0cffdac, template support has been dropped. It's still accessible from prawn and just started to cause errors in my app, after upgrading to 1.0.0:

`NoMethodError: undefined method `load_file' for #<PDF::Core::ObjectStore:0x007f81f3dc4340>`

Is there any alternative solution available or any chance of reverting the above mentioned commit?
